language: bash
sudo: required
services: docker

env:
  - VERSION=1.2

before_install:
    - cd "$VERSION"
    - docker build -t docker-murmur .
    - docker run -d -p 64738:64738 docker-murmur

script:
  - docker ps | grep docker-murmur
